#!/bin/bash

VERSTRING="2008.04.25-001"
VERSION="$( basename "$0" ) version ${VERSTRING}.

\"Few desire liberty; most wish only for a just master.\"
        -- Sallust, as the Roman Republic became the Empire"

### Big text chunks

USAGE="Usage: $( basename "$0" ) filename

This is a shell script.  A description of what it does should go
here.

Arguments:
  filename                  A file.

Options:
  -h, --help                Display this help.
  -v, --version             Show version information.
  --license                 Show license information.

Requires:
  nothing                   No dependecies other than normal
                            tools.

See also http://www.cheshirehall.org/

Copyright (c) 2007 Evan 'JabberWokky' Edwards
Released under the terms of the MIT/X11 License (see --license for details)"

LICENSE="Copyright (c) 2007 Evan 'JabberWokky' Edwards

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the \"Software\"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE."

### Defaults

QUIET=""
DIRORIGINAL="$( pwd )"


### Support functions

function exitwith
{
  echo "${*}"
  exit
}


### Process options (short form, use this OR the one below)

ARG="$1"

[ "$ARG" == "-h" ]                        && ARG='--help'
[ "$ARG" == "-v" ]                        && ARG='--version'

[ "$ARG" == "--help" ]                    && exitwith "$USAGE"
[ "$ARG" == "--license" ]                 && exitwith "$LICENSE"
[ "$ARG" == "--version" ]                 && exitwith "$VERSION"


### Process options (long form, use this OR the one above)

while [ "${1:0:1}" == "-" ]
do
  case "${1:1}" in

    h|-help)       exitwith "$USAGE"     ;;
    l|-license)    exitwith "$LICENSE"   ;;
    q|-quiet)      QUIET="1"             ;;
    v|-version)    exitwith "$VERSION"   ;;

    *)             exitwith "$USAGE" ;;
  esac
  shift
done


### Validate input

FILENAME="$1"
[ "$FILENAME" == "" ]                     && exitwith "$USAGE"


#######################################################################
### Run the thing


if [ "$FILENAME" == "out" ]
then
  cat $0 |sed "s/$VERSTRING/$( date +%Y.%m.%d )-001/"
else
  echo -n "Hello World!  I was run with $FILENAME which "
  [ -f "$FILENAME" ] && echo exists. || echo does not exist.
  echo -e "\nRun with \"out\" to dump self"
fi
